services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: book_store
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - ./book_shop_backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./book_shop_backend/views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - 2345:5432

  backend:
    build: /book_shop_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      FRONTEND_HOST: localhost
      FRONTEND_PORT: 3000

    ports:
      - 8080:8080

  frontend:
    build:
      context: ./book_shop_frontend
      args:
        VITE_BACKEND_HOST: localhost #this would be "backend" for production.
        VITE_BACKEND_PORT: 8080
    depends_on:
      - backend
    ports:
      - 3000:80
volumes:
  pgdata:
