apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: project-namespace
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None
