apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: project-namespace
spec:
  selector:
    app: frontend-vue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
