apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: project-namespace
  labels:
    app: frontend-vue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-vue
  template:
    metadata:
      labels:
        app: frontend-vue
    spec:
      containers:
        - name: frontend-vue
          image: toosie25/book-shop-frontend:latest
          ports:
            - containerPort: 80
#          envFrom:
#            - configMapRef:
#                name: frontend-config
