
    create table "author" (
        "country_id" bigint,
        "id" bigint generated by default as identity,
        "name" varchar(255),
        "surname" varchar(255),
        primary key ("id")
    );

    create table "book" (
        "available_copies" integer,
        "category" smallint check ("category" between 0 and 6),
        "date_published" date,
        "is_soft_deleted" boolean,
        "author_id" bigint,
        "id" bigint generated by default as identity,
        "name" varchar(255),
        primary key ("id")
    );

    create table "country" (
        "id" bigint generated by default as identity,
        "continent" varchar(255),
        "name" varchar(255),
        primary key ("id")
    );

    create table "library_users" (
        "is_account_non_expired" boolean not null,
        "is_account_non_locked" boolean not null,
        "is_credentials_non_expired" boolean not null,
        "is_enabled" boolean not null,
        "name" varchar(255),
        "password" varchar(255),
        "role" varchar(255) check ("role" in ('ROLE_USER','ROLE_LIBRARIAN','ROLE_ADMIN')),
        "surname" varchar(255),
        "username" varchar(255) not null,
        primary key ("username")
    );

    create table "library_users_wish_listed_books" (
        "wish_listed_books_id" bigint not null,
        "user_username" varchar(255) not null
    );

    alter table if exists "author" 
       add constraint "FKqj02kdlx8vucwjltgudd752x3" 
       foreign key ("country_id") 
       references "country";

    alter table if exists "book" 
       add constraint "FKsytpuhl67g1174cx7iqlw6os9" 
       foreign key ("author_id") 
       references "author";

    alter table if exists "library_users_wish_listed_books" 
       add constraint "FK5mtc2q4fitwdt4pvfjo9y77xu" 
       foreign key ("wish_listed_books_id") 
       references "book";

    alter table if exists "library_users_wish_listed_books" 
       add constraint "FKqou794qgjdud1jdti80cvtb9o" 
       foreign key ("user_username") 
       references "library_users";
