name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_BACKEND: toosie25/book-shop-backend
      IMAGE_FRONTEND: toosie25/book-shop-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ var.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./book_shop_backend
          file: ./book_shop_backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./book_shop_frontend
          file: ./book_shop_frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}:latest
